robot_id: "1"
robot_name: "robot_Z"
# 0329 company  4800 dog
# map_frame_id: "odom"
# sensor_frame_id: "base_footprint"
# robot_base_frame_id: "base_footprint"
# track_point_frame_id: "base_footprint"

# 0329 lio global 4800 dog
# map_frame_id: "map"
# sensor_frame_id: "/body"
# robot_base_frame_id: "/body"
# track_point_frame_id: "/body"

# x20 on offline tf
# map_frame_id: "camera_init"
# sensor_frame_id: "/rslidar"
# robot_base_frame_id: "/rslidar"
# track_point_frame_id: "/rslidar"

# x20 on board
map_frame_id: "odom"
sensor_frame_id: "/rslidar"
robot_base_frame_id: "/rslidar"
track_point_frame_id: "/rslidar"

# x20 dog gazebo sim
# map_frame_id: "odom"
# sensor_frame_id: "/velodyne2"
# robot_base_frame_id: "/velodyne2"
# track_point_frame_id: "/velodyne2"


robot_pose_with_covariance_topic: ""
robot_pose_cache_size: 200
robot_local_map_size: 3
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
map_saving_file: "/home/mav-lab/slam_ws/test.pcd"
submap_saving_dir: "/home/mav-lab/submaps/"
camera_params_yaml: "/home/twilight/project/robot/hedian_jypro/GEM_main_0804/src/elevation_mapping/yq_intrinsic.yaml"


orthomosaic_saving_dir: "/home/mav-lab/Datasets/zjg_image/"
