robot_id: "0"
robot_name: "robot0"
map_frame_id: "/robot0/map"
sensor_frame_id: "/velodyne"
robot_base_frame_id: "/velodyne"
track_point_frame_id: "/velodyne"
robot_pose_cache_size: 200
robot_local_map_size: 10
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
octomap_road_resolution: 0.2
octomap_obs_resolution: 0.1
map_saving_file: "./map.pcd"
submap_saving_dir: "./submaps/"
camera_params_yaml: "/home/mav-lab/Projects/git_backup/GEM_ws/src/elevation_mapping/kitti_intrinsic.yaml"
orthomosaic_saving_dir: "./image/"
